apiVersion: v1
kind: ServiceAccount
metadata:
  name: park-sa
  namespace: {{ $.Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.environment_name }}-park-sa@{{ .Values.gc_project_id }}.iam.gserviceaccount.com"