services:
  backend:
    image: denoland/deno:debian
    container_name: backend
    ports:
      - "6969:6969"
    environment:
      - PORT=6969
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
    working_dir: /app/backend
    command: bash -c "deno run --allow-all --watch main.ts"

  frontend:
    image: node:20
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared
    working_dir: /app/frontend
    command: bash -c "npm install && npm start"