services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "6969:6969"
    environment:
      - PORT=6969

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - PARK_BACKEND_URL=http://localhost:6969