apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-frontend
  labels:
    app: {{ include "my-app.fullname" . }}
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "my-app.fullname" . }}
    component: frontend
