apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-property-management
  labels:
    app: {{ include "my-app.fullname" . }}
    component: property-management
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.propertyManagement.service.port }}
      targetPort: {{ .Values.propertyManagement.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "my-app.fullname" . }}
    component: property-management
