apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.propertyManagement.service.name }}
  labels:
    app: {{ .Release.Name }}
    component: property-management
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.propertyManagement.service.port }}
      targetPort: {{ .Values.propertyManagement.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
    component: property-management
