networks:
  k6:
    name: k6
  grafana:

volumes:
  influxdb:

services:
  influxdb:
    container_name: load-test-influx
    image: influxdb:1.11
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
      - influxdb:/var/lib/influxdb

  grafana:
    container_name: load-test-grafana
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=true
    volumes:
      - ./grafana:/etc/grafana/provisioning/