apiVersion: v1
kind: ServiceAccount
metadata:
  name: authentication-service-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ $.Release.Namespace }}-auth@{{ .Values.gcp.project_id }}.iam.gserviceaccount.com"