apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-parking-management
  labels:
    app: {{ .Release.Name }}
    component: parking-management
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: parking-management
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: parking-management
    spec:
      serviceAccountName: {{ .Values.parkingManagement.serviceAccount.name }}
      containers:
        - name: parking-management
          image: "{{ .Values.repository }}/{{.Values.parkingManagement.image.name}}:{{ .Values.gitTag }}"
          imagePullPolicy: {{ .Values.parkingManagement.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.parkingManagement.service.port }}
          env:
            - name: FIRESTORE_DB_ID
              value: "{{ .Values.parkingManagement.env.fireStoreDbId }}"
            - name: PORT
              value: "{{ .Values.parkingManagement.service.port }}"