apiVersion: v1
kind: ServiceAccount
metadata:
  name: property-management-sa
  namespace: {{ $.Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ $.Release.Namespace }}-property-management-sa@{{ .Values.gcp.project_id }}.iam.gserviceaccount.com"