apiVersion: v1
kind: ServiceAccount
metadata:
  name: prop-sa
  namespace: {{ $.Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.environment_name }}-prop-sa@{{ .Values.gc_project_id }}.iam.gserviceaccount.com"