apiVersion: v1
kind: ServiceAccount
metadata:
  name: property-management-sa
  namespace: {{ $.Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.tenant_id }}-prop@{{ .Values.gcp.project_id }}.iam.gserviceaccount.com"