apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-property-management
  labels:
    app: {{ .Release.Name }}
    component: property-management
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: property-management
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: property-management
    spec:
      serviceAccountName: {{ .Values.propertyManagement.serviceAccount.name }}
      containers:
        - name: property-management
          image: "{{ .Values.repository }}/{{.Values.propertyManagement.image.name}}:{{ .Values.gitTag }}"
          imagePullPolicy: {{ .Values.propertyManagement.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.propertyManagement.service.port }}
          env:
            - name: FIRESTORE_DB_ID
              value: "{{ .Values.gc_project_id }}-prop-ma-{{ .Release.Namespace }}"
            - name: GCS_BUCKET_ID
              value: "{{ .Values.gc_project_id }}-prop-ma-{{ .Release.Namespace }}"
            - name: PORT
              value: "{{ .Values.propertyManagement.service.port }}"
            - name: PARKING_MANAGEMENT_BACKEND_URL
              value: "http://{{ .Values.parkingManagement.service.name }}:{{ .Values.parkingManagement.service.port }}"
          livenessProbe:
            httpGet:
              path: {{ .Values.propertyManagement.healthCheck.endpoint }}
              port: {{ .Values.propertyManagement.service.port }}
            initialDelaySeconds: {{ .Values.propertyManagement.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.propertyManagement.healthCheck.periodSeconds }}
