apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authentication-service-external
spec:
  parentRefs:
    - kind: Gateway
      name: {{ .Values.gateway.name }}
      namespace: {{ .Release.Namespace }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.authenticationService.route.prefix }}
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: authentication-service
          port: {{ .Values.authenticationService.service.port }}