apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  annotations:
    networking.gke.io/managed-certificates: "park-certificate"
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
  addresses:
    - type: NamedAddress
      value: {{ .Values.gateway.ipName }}