replicaCount: 1

repository: ""
gitTag: ""

gc_project_id: "PROJECT_ID"

identityPlatForm:
  apiKey: "API_KEY"
  authDomain: "AUTH_DOMAIN"

gateway:
  name: "park-external-http"
  namespace: "infra-ns"

domain: null
subdomain: null
environment_name: null
tenant_id: null
tenant_type: null

resources:
  free:
    requests:
      cpu: "3"
      memory: "3Gi"
    limits:
      cpu: "5"
      memory: "5Gi"
  premium:
    requests:
      cpu: "4"
      memory: "4Gi"
    limits:
      cpu: "8"
      memory: "8Gi"
  enterprise:
    requests:
      cpu: "5"
      memory: "5Gi"
    limits:
      cpu: "10"
      memory: "10Gi"

authenticationService:
  url: ""
infrastructureManagement:
  url: ""
infrastructureAdministration:
  audience: "infrastructure-administration-service"

propertyManagement:
  image:
    name: "property-management"
    pullPolicy: IfNotPresent
  service:
    port: 8080
  route:
    prefix: "/property"
  healthCheck:
    endpoint: "/livez"
    initialDelaySeconds: 3
    periodSeconds: 5
    timeoutSeconds: 3

parkingManagement:
  image:
    name: "parking-management"
    pullPolicy: IfNotPresent
  service:
    port: 8081
  route:
    prefix: "/parking"
  healthCheck:
    endpoint: "/livez"
    initialDelaySeconds: 3
    periodSeconds: 5
    timeoutSeconds: 3
