apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}
    component: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: frontend
    spec:
      serviceAccountName: {{ .Values.frontend.serviceAccount.name }}
      containers:
        - name: frontend
          image: "{{ .Values.repository }}/{{.Values.frontend.image.name}}:{{ .Values.gitTag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          env:
            - name: PARK_PROPERTY_MANAGEMENT_URL
              value: "{{ .Values.frontend.env.BackendUrl }}/property-management"
            - name: PARK_PARKING_MANAGEMENT_URL
              value: "{{ .Values.frontend.env.BackendUrl }}/parking-management"
            - name: PARK_AUTHENTICATION_URL
              value: "{{ .Values.frontend.env.BackendUrl }}/authentication-service"
            - name: PARK_IDENTITY_PLATFORM_API_KEY
              value: {{ .Values.identityPlatForm.apiKey }}
            - name: PARK_IDENTITY_PLATFORM_AUTH_DOMAIN
              value: {{ .Values.identityPlatForm.authDomain }}
            - name: PARK_IDENTITY_PLATFORM_PROJECT_ID
              value: {{ .Values.gc_project_id }}
            {{ if .Values.identityPlatForm.tenantId }}
            - name: PARK_TENANT_ID
              value: {{ .Values.identityPlatForm.tenantId }}
            {{ end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.healthCheck.endpoint }}
              port: {{ .Values.frontend.service.port }}
            initialDelaySeconds: {{ .Values.frontend.healthCheck.initialDelaySeconds }}
            periodSeconds:  {{ .Values.frontend.healthCheck.periodSeconds }}