apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: frontend-external
spec:
  parentRefs:
    - kind: Gateway
      name: {{ .Values.gateway.name }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.frontend.service.name }}
          port: {{ .Values.frontend.service.port }}