apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Namespace }}-frontend-external
spec:
  parentRefs:
    - kind: Gateway
      name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  hostnames:
    - {{ .Values.subdomain }}.{{ .Values.domain }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.frontend.route.prefix }}
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: frontend
          port: {{ .Values.frontend.service.port }}