apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: {{ .Release.Namespace }}
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Namespace }}
    component: frontend
