apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: park-{{ .Release.Namespace }}
    component: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: park-{{ .Release.Namespace }}
      component: frontend
  template:
    metadata:
      labels:
        app: park-{{ .Release.Namespace }}
        component: frontend
    spec:
      serviceAccountName: front-sa
      containers:
        - name: frontend
          image: "{{ .Values.repository }}/{{.Values.frontend.image.name}}:{{ .Values.gitTag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          env:
            - name: PARK_PROPERTY_MANAGEMENT_URL
              value: "{{ .Values.frontend.env.propertyUrl }}"
            - name: PARK_PARKING_MANAGEMENT_URL
              value: "{{ .Values.frontend.env.parkingUrl }}"
            - name: PARK_AUTHENTICATION_URL
              value: "{{ .Values.frontend.env.authUrl }}"
            - name: PARK_INFRASTRUCTURE_MANAGEMENT_URL
              value: "{{ .Values.frontend.env.infrastructureUrl}}"

            - name: PARK_IDENTITY_PLATFORM_API_KEY
              value: {{ .Values.identityPlatForm.apiKey }}
            - name: PARK_IDENTITY_PLATFORM_AUTH_DOMAIN
              value: {{ .Values.identityPlatForm.authDomain }}
            - name: PARK_IDENTITY_PLATFORM_PROJECT_ID
              value: {{ .Values.gc_project_id }}

            - name: PARK_TENANT_ID
              value: {{ .Values.tenant_id }}
            - name: PARK_TENANT_TYPE
              value: {{ .Values.tenant_type }}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "256m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.healthCheck.endpoint }}
              port: {{ .Values.frontend.service.port }}
            initialDelaySeconds: {{ .Values.frontend.healthCheck.initialDelaySeconds }}
            periodSeconds:  {{ .Values.frontend.healthCheck.periodSeconds }}