apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: {{ $.Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.tenantId }}-front@{{ .Values.gc_project_id }}.iam.gserviceaccount.com"