apiVersion: v1
kind: ServiceAccount
metadata:
  name: front-sa
  namespace: {{ $.Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.tenant_id }}-front-sa@{{ .Values.gc_project_id }}.iam.gserviceaccount.com"