name: Build and Test

on:
  pull_request:
    branches:
      - main
      - dev

permissions:
  id-token: write 
  contents: read 
  pull-requests: write

env:
  TAG_ID: ${{ github.sha }}
  TERRAFORM_PLAN_ENVIRONMENT: staging

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - { name: "property-management", dockerfile: "./property-management.Dockerfile" }
          - { name: "parking-management", dockerfile: "./parking-management.Dockerfile" }
          - { name: "authentication-service", dockerfile: "./authentication-service.Dockerfile" }
          - { name: "infrastructure-administration", dockerfile: "./infrastructure-administration.Dockerfile" }
          - { name: "frontend", dockerfile: "./frontend.Dockerfile" }
          - { name: "signup-frontend", dockerfile: "./signup-frontend.Dockerfile" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build \
            -f ${{ matrix.service.dockerfile }} \
            . \
            --platform linux/amd64

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [
          backend/property-management,
          backend/parking-management
        ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd ${{ matrix.service }}
        npm ci

    - name: Run tests
      run: |
        cd ${{ matrix.service }}
        npm test --if-present

  plan-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r ci-cd/requirements.txt

      - name: Login to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: 'github-sa@${{ vars.STAGING_PROJECT_ID }}.iam.gserviceaccount.com'
          workload_identity_provider: '${{ secrets.STAGING_WORKLOAD_IDENTITY_PROVIDER }}'
      
      - uses: hashicorp/setup-terraform@v3
      - name: Run Terraform plan
        working-directory: ./ci-cd/terraform/${{ env.TERRAFORM_PLAN_ENVIRONMENT}}
        run: |
          terraform init
          terraform plan \
            -var="is_github_actions=true" \
            -var="project_id=${{ vars.STAGING_PROJECT_ID }}" \
            -var="region=${{ vars.STAGING_REGION }}" \
            -var="domain_name=${{ vars.STAGING_DOMAIN }}" \
            -var="create_cluster=true"
            -var="git_tag=${{ env.TAG_ID }}"
            -var="identity_api_key=${{ secrets.identity_platform_api_key }}"
            -var="identity_auth_domain=${{ vars.STAGING_PROJECT_ID }}.firebaseapp.com"