name: Build and Test

on:
  pull_request:
    branches:
      - main
      - dev

permissions:
  id-token: write 
  contents: read 
  pull-requests: write

env:
  DOMAIN: ${{ vars.STAGING_DOMAIN }}
  TERRAFORM_PLAN_ENVIRONMENT: staging

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - { name: "property-management", dockerfile: "./property-management.Dockerfile" }
          - { name: "parking-management", dockerfile: "./parking-management.Dockerfile" }
          - { name: "authentication-service", dockerfile: "./authentication-service.Dockerfile" }
          - { name: "infrastructure-administration", dockerfile: "./infrastructure-administration.Dockerfile" }
          - { name: "frontend", dockerfile: "./frontend.Dockerfile" }
          - { name: "signup-frontend", dockerfile: "./signup-frontend.Dockerfile" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build \
            -f ${{ matrix.service.dockerfile }} \
            . \
            --platform linux/amd64

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [
          backend/property-management,
          backend/parking-management
        ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd ${{ matrix.service }}
        npm ci

    - name: Run tests
      run: |
        cd ${{ matrix.service }}
        npm test --if-present

  plan-terraform:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r ci-cd/requirements.txt

      - name: Login to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: '${{ secrets.STAGING_GITHUB_SA }}'
          workload_identity_provider: '${{ secrets.STAGING_WORKLOAD_IDENTITY_PROVIDER }}'
      
      - uses: hashicorp/setup-terraform@v3
      - name: Run Terraform plan
        working-directory: ./ci-cd
        run: |
          python -u deploy-terraform.py \
          --action plan \
          --is-github-actions \
          --create-cluster \
          --project-id ${{ vars.STAGING_PROJECT_ID }} \
          --gcs-bucket ${{ vars.STAGING_STATE_BUCKET }} \
          --domain-name ${{ env.DOMAIN }} \
          --region ${{ vars.REGION }} \
          --environment ${{ env.TERRAFORM_PLAN_ENVIRONMENT }}