name: Deploy to Staging Free

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: "Git tag to deploy"
        required: true
      branch:
        description: 'The branch to run this workflow on'
        required: true
        default: 'dev'

permissions:
  id-token: write 
  contents: read 
  
env:
  GCR_REPO: "${{ vars.REGION }}-docker.pkg.dev/${{ vars.STAGING_PROJECT_ID }}/${{ vars.STAGING_ARTIFACT_REPO }}"

jobs:
  deployment-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Login to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: '${{ secrets.STAGING_GITHUB_SA }}'
          workload_identity_provider: '${{ secrets.STAGING_WORKLOAD_IDENTITY_PROVIDER }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: ${{ vars.STAGING_CLUSTER_NAME }}
          location: ${{vars.REGION}}
            
      - name: Wait for API gateway IP assignment
        run: |
          # Loop until the API gateway has an assigned external IP.
          for i in {1..30}; do
            IP=$(kubectl -n infra-ns get gateway -o jsonpath="{.items[0].status.addresses[0].value}")
            if [ -n "$IP" ] && [ "$IP" != "<pending>" ]; then
              echo "API gateway IP found: $IP"
              echo "BACKEND_INGRESS=http://$IP" >> $GITHUB_ENV
              break
            fi
            echo "Waiting for the API gateway external IP..."
            sleep 10
          done
          if [ -z "$IP" ] || [ "$IP" == "<pending>" ]; then
            echo "Timed out waiting for the API gateway external IP."
            exit 1
          fi
      
      - name: Deploy backend
        run: |
          helm upgrade --install park-backend ./helm/backend \
            --namespace ${{ vars.GKE_FREE_NAMESPACE }} \
            --create-namespace \
            --set repository=${{ env.GCR_REPO }} \
            --set gitTag=${{ inputs.git_tag }} \
            --set identityPlatForm.apiKey=${{ secrets.STAGING_IDENTITY_PLATFORM_API_KEY }} \
            --set identityPlatForm.authDomain=${{ vars.STAGING_IDENTITY_PLATFORM_AUTH_DOMAIN }} \
            --set gc_project_id=${{ vars.STAGING_PROJECT_ID }}

      - name: Deploy frontend
        run: |
          helm upgrade --install park-frontend ./helm/frontend \
            --namespace ${{ vars.GKE_FREE_NAMESPACE }} \
            --create-namespace \
            --set repository=${{ env.GCR_REPO }} \
            --set gitTag=${{ inputs.git_tag }} \
            --set identityPlatForm.apiKey=${{ secrets.STAGING_IDENTITY_PLATFORM_API_KEY }} \
            --set identityPlatForm.authDomain=${{ vars.STAGING_IDENTITY_PLATFORM_AUTH_DOMAIN }} \
            --set gc_project_id=${{ vars.STAGING_PROJECT_ID }} \
            --set backendUrl=$BACKEND_INGRESS \