name: Manage tenant

on:
  # Reusable workflows must define `workflow_call` instead of `workflow_dispatch`.
  workflow_call:
    # 1) Generic environment inputs
    inputs:
      environment:
        type: string
        description: "Which environment (e.g. 'staging' or 'production')?"
        required: true
      project_id:
        type: string
        required: true
      project_number:
        type: string
        required: true
      region:
        type: string
        required: true
      domain:
        type: string
        required: true
      state_bucket:
        type: string
        required: true

      # 2) Tenant inputs (originally from `workflow_dispatch`)
      tenant_action:
        type: string
        required: true
        description: "add or remove"
      tenant_id:
        type: string
        required: true
      tenant_subdomain:
        type: string
        required: true

    # 3) Secrets
    secrets:
      workload_identity_provider:
        required: true
      identity_platform_api_key:
        required: true

permissions:
  id-token: write
  contents: read

env:
  TAG_ID: ${{ github.sha }}

jobs:
  manage-tenant:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: "github-sa@${{ inputs.project_id }}.iam.gserviceaccount.com"
          workload_identity_provider: ${{ secrets.workload_identity_provider }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"
      - run: pip install -r ci-cd/requirements.txt

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - uses: hashicorp/setup-terraform@v3

      - name: Manage enterprise tenants
        working-directory: ./ci-cd
        run: |
          python -u manage_enterprise_tenants.py \
            --action ${{ inputs.tenant_action }} \
            --gcs-bucket ${{ inputs.state_bucket }} \
            --tenant-id ${{ inputs.tenant_id }} \
            --tenant-subdomain ${{ inputs.tenant_subdomain }}

  sync-terraform:
    runs-on: ubuntu-latest
    needs: manage-tenant
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: "github-sa@${{ inputs.project_id }}.iam.gserviceaccount.com"
          workload_identity_provider: ${{ secrets.workload_identity_provider }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"
      - run: pip install -r ci-cd/requirements.txt

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - uses: hashicorp/setup-terraform@v3

      - uses: hashicorp/setup-terraform@v3
      - name: Terraform apply
        working-directory: ./ci-cd/terraform/${{ inputs.environment }}
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="is_github_actions=true" \
            -var="project_id=${{ inputs.project_id }}" \
            -var="region=${{ inputs.region }}" \
            -var="domain_name=${{ inputs.domain }}" \
            -var="create_cluster=true" \
            -var="git_tag=${{ env.TAG_ID }}" \
            -var="identity_api_key=${{ secrets.identity_platform_api_key }}" \
            -var="identity_auth_domain=${{ inputs.project_id }}.firebaseapp.com"