name: Manage tenant

on:
  # Reusable workflows must define `workflow_call` instead of `workflow_dispatch`.
  workflow_call:
    # 1) Generic environment inputs
    inputs:
      environment:
        type: string
        description: "Which environment (e.g. 'staging' or 'production')?"
        required: true
      project_id:
        type: string
        required: true
      project_number:
        type: string
        required: true
      region:
        type: string
        required: true
      domain:
        type: string
        required: true
      state_bucket:
        type: string
        required: true

      # 2) Tenant inputs (originally from `workflow_dispatch`)
      tenant_action:
        type: string
        required: true
        description: "add or remove"
      tenant_id:
        type: string
        required: true
      tenant_subdomain:
        type: string
        required: true

    # 3) Secrets
    secrets:
      workload_identity_provider:
        required: true
      identity_platform_api_key:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  manage-tenant:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
            ref: ${{ inputs.environment == 'production' && 'main' || 'dev' }}

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: "github-sa@${{ inputs.project_id }}.iam.gserviceaccount.com"
          workload_identity_provider: ${{ secrets.workload_identity_provider }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"
      - run: pip install -r ci-cd/requirements.txt

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Manage enterprise tenants
        working-directory: ./ci-cd
        run: |
          python -u manage_enterprise_tenants.py \
            --action ${{ inputs.tenant_action }} \
            --gcs-bucket ${{ inputs.state_bucket }} \
            --tenant-id ${{ inputs.tenant_id }} \
            --tenant-subdomain ${{ inputs.tenant_subdomain }}

  sync-services:
    runs-on: ubuntu-latest
    needs: manage-tenant
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: "github-sa@${{ inputs.project_id }}.iam.gserviceaccount.com"
          workload_identity_provider: ${{ secrets.workload_identity_provider }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Check for deployment.json
        run: |
          BUCKET_NAME="${{ inputs.project_id }}-terraform-state"
          OBJECT_PATH="deployment.json"
          
          # Check if the file exists in GCS; if not, exit 1 to fail the job
          if ! gsutil -q stat "gs://${BUCKET_NAME}/${OBJECT_PATH}"; then
            echo "🚫 deployment.json not found in GCS bucket. Failing."
            exit 1
          fi

          # If the file exists, read it into a variable
          CONTENT=$(gsutil cat "gs://${BUCKET_NAME}/${OBJECT_PATH}" | jq -c .)
          
          # Parse git_tag using jq (assuming your file has a structure like { "git_tag": "somevalue" })
          GIT_TAG=$(echo "$CONTENT" | jq -r .git_tag)
          
          # Optionally check if no git_tag field is present or is empty
          if [ -z "$GIT_TAG" ] || [ "$GIT_TAG" = "null" ]; then
            echo "🚫 'git_tag' was not set in deployment.json. Failing."
            exit 1
          fi

          # Export it for subsequent steps to use
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV

      - name: Fetch enterprise-tenants.json or default to []
        run: |
          BUCKET_NAME="${{ inputs.project_id }}-terraform-state"
          OBJECT_PATH="enterprise-tenants.json"

          # Default empty JSON array
          CONTENT="[]"

          # Check if file exists in GCS
          if gsutil -q stat "gs://${BUCKET_NAME}/${OBJECT_PATH}"; then
              echo "✔ enterprise-tenants.json found; fetching from GCS..."
              CONTENT=$(gsutil cat "gs://${BUCKET_NAME}/${OBJECT_PATH}" | jq -c . || echo "[]")
          else
              echo "✖ enterprise-tenants.json not found. Using empty array."
          fi

          # Safely set as a single-line JSON environment variable
          echo "ENTERPRISE_TENANTS_JSON=$(echo $CONTENT | jq -c .)" >> $GITHUB_ENV

      - uses: hashicorp/setup-terraform@v3
      - name: Terraform apply
        working-directory: ./ci-cd/terraform/${{ inputs.environment }}
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="is_github_actions=true" \
            -var="project_id=${{ inputs.project_id }}" \
            -var="region=${{ inputs.region }}" \
            -var="domain_name=${{ inputs.domain }}" \
            -var="git_tag=$GIT_TAG" \
            -var="enterprise_tenants_json=$ENTERPRISE_TENANTS_JSON"