name: Create Tenant

on:
  workflow_dispatch:
    inputs:
      tenant_id:
        required: true
      tenant_subdomain:
        required: true
      
permissions:
  id-token: write 
  contents: read 
  
env:
  GCR_REPO: "${{ vars.REGION }}-docker.pkg.dev/${{ vars.STAGING_PROJECT_ID }}/${{ vars.STAGING_ARTIFACT_REPO }}"
  CLUSTER: "${{ vars.STAGING_PROJECT_ID }}-gke"
  DOMAIN: ${{ vars.STAGING_DOMAIN }}

jobs:
  create-tenant:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: '${{ secrets.STAGING_GITHUB_SA }}'
          workload_identity_provider: '${{ secrets.STAGING_WORKLOAD_IDENTITY_PROVIDER }}'

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r ci-cd/requirements.txt

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - uses: hashicorp/setup-terraform@v3
      - name: Run deploy script
        working-directory: ./ci-cd
        run: |
          python manage_enterprise_tenants.py \
          --action add \
          --gcs-bucket ${{ vars.STAGING_STATE_BUCKET }} \
          --tenant-id ${{ inputs.tenant_id }} \
          --tenant-subdomain ${{ inputs.tenant_subdomain }} \
    
  deploy-terraform:
    runs-on: ubuntu-latest
    needs: create-tenant
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: '${{ secrets.STAGING_GITHUB_SA }}'
          workload_identity_provider: '${{ secrets.STAGING_WORKLOAD_IDENTITY_PROVIDER }}'

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r ci-cd/requirements.txt

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - uses: hashicorp/setup-terraform@v3
      - name: Run terraform apply
        working-directory: ./ci-cd
        run: |
          python deploy-terraform.py \
          --action apply \
          --is-github-actions \
          --create-cluster \
          --project-id ${{ vars.STAGING_PROJECT_ID }} \
          --gcs-bucket ${{ vars.STAGING_STATE_BUCKET }} \
          --domain-name ${{ env.DOMAIN }} \
          --region ${{ vars.REGION }}

  deploy-services:
    runs-on: ubuntu-latest
    needs: deploy-terraform
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SERVICE_AUDIENCE: "infrastructure-administration-service"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: '${{ secrets.STAGING_GITHUB_SA }}'
          workload_identity_provider: '${{ secrets.STAGING_WORKLOAD_IDENTITY_PROVIDER }}'

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: ${{ env.CLUSTER }}
          location: ${{ vars.REGION }}
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r ci-cd/requirements.txt

      - name: Retrieve infrastructure administration service URL
        run: |
          echo "INFRASTRUCTURE_SERVICE_URL=$(gcloud run services describe infrastructure-administration --platform=managed --region=${{ vars.REGION }} --format 'value(status.url)')" >> $GITHUB_ENV
      
      - name: Install Helm charts
        working-directory: ./ci-cd
        run: |
          python deploy-kubernetes.py \
          --is-github-actions \
          --project-id ${{ vars.STAGING_PROJECT_ID }} \
          --gcs-bucket ${{ vars.STAGING_STATE_BUCKET }} \
          --repository ${{ env.GCR_REPO }} \
          --identity-api-key ${{ secrets.STAGING_IDENTITY_PLATFORM_API_KEY }}  \
          --identity-auth-domain ${{ vars.STAGING_IDENTITY_PLATFORM_AUTH_DOMAIN }} \
          --infra-url $INFRASTRUCTURE_SERVICE_URL \
          --domain ${{ env.DOMAIN }} \
          --region ${{ vars.REGION }}